const data = {
  1: {
    1: [
      { cn: "你", pinyin: "nǐ", th: "คุณ/เธอ" },
      { cn: "好", pinyin: "hǎo", th: "ดี" },
      { cn: "你好", pinyin: "nǐ hǎo", th: "สวัสดี" },
      { cn: "一", pinyin: "yī", th: "หนึ่ง" },
      { cn: "五", pinyin: "wǔ", th: "ห้า" },
      { cn: "八", pinyin: "bā", th: "แปด" },
      { cn: "大", pinyin: "dà", th: "ใหญ่" },
      { cn: "不", pinyin: "bù", th: "ไม่" },
      { cn: "口", pinyin: "kǒu", th: "ปาก (หรือลักษณนามคนในครอบครัว)" },
      { cn: "白", pinyin: "bái", th: "ขาว" },
      { cn: "女", pinyin: "nǚ", th: "หญิง" },
      { cn: "马", pinyin: "mǎ", th: "ม้า" }
    ],
    2: [
      { cn: "忙", pinyin: "máng", th: "ยุ่ง" },
      { cn: "吗", pinyin: "ma", th: "ไหม (คำถาม)" },
      { cn: "很", pinyin: "hěn", th: "มาก" },
      { cn: "汉语", pinyin: "Hànyǔ", th: "ภาษาจีน" },
      { cn: "难", pinyin: "nán", th: "ยาก" },
      { cn: "太", pinyin: "tài", th: "เกินไป" },
      { cn: "爸爸", pinyin: "bàba", th: "พ่อ" },
      { cn: "妈妈", pinyin: "māma", th: "แม่" },
      { cn: "他", pinyin: "tā", th: "เขา (ชาย)" },
      { cn: "她", pinyin: "tā", th: "เขา (หญิง)" },
      { cn: "男", pinyin: "nán", th: "ชาย" },
      { cn: "哥哥", pinyin: "gēge", th: "พี่ชาย" },
      { cn: "弟弟", pinyin: "dìdi", th: "น้องชาย" },
      { cn: "妹妹", pinyin: "mèimei", th: "น้องสาว" }
    ],
    3: [
      { cn: "学", pinyin: "xué", th: "เรียน" },
      { cn: "英语", pinyin: "Yīngyǔ", th: "ภาษาอังกฤษ" },
      { cn: "阿拉伯语", pinyin: "Ālābóyǔ", th: "ภาษาอาหรับ" },
      { cn: "德语", pinyin: "Déyǔ", th: "ภาษาเยอรมัน" },
      { cn: "俄语", pinyin: "Éyǔ", th: "ภาษารัสเซีย" },
      { cn: "法语", pinyin: "Fǎyǔ", th: "ภาษาฝรั่งเศส" },
      { cn: "韩国语", pinyin: "Hánguóyǔ", th: "ภาษาเกาหลี" },
      { cn: "日语", pinyin: "Rìyǔ", th: "ภาษาญี่ปุ่น" },
      { cn: "西班牙语", pinyin: "Xībānyáyǔ", th: "ภาษาสเปน" },
      { cn: "去", pinyin: "qù", th: "ไป" },
      { cn: "对", pinyin: "duì", th: "ถูกต้อง/ใช่" },
      { cn: "邮局", pinyin: "yóujú", th: "ไปรษณีย์" },
      { cn: "寄", pinyin: "jì", th: "ส่ง (จดหมาย/พัสดุ)" },
      { cn: "信", pinyin: "xìn", th: "จดหมาย" },
      { cn: "银行", pinyin: "yínháng", th: "ธนาคาร" },
      { cn: "取", pinyin: "qǔ", th: "ถอน(เงิน)/เอา(ของ)" },
      { cn: "钱", pinyin: "qián", th: "เงิน" },
      { cn: "明天", pinyin: "míngtiān", th: "พรุ่งนี้" },
      { cn: "天", pinyin: "tiān", th: "วัน/ท้องฟ้า" },
      { cn: "见", pinyin: "jiàn", th: "พบ/เจอ" },
      { cn: "六", pinyin: "liù", th: "หก" },
      { cn: "七", pinyin: "qī", th: "เจ็ด" },
      { cn: "九", pinyin: "jiǔ", th: "เก้า" }
    ],
    4: [
      { cn: "今天", pinyin: "jīntiān", th: "วันนี้" },
      { cn: "昨天", pinyin: "zuótiān", th: "เมื่อวาน" },
      { cn: "星期", pinyin: "xīngqī", th: "สัปดาห์" },
      { cn: "星期一", pinyin: "Xīngqīyī", th: "วันจันทร์" },
      { cn: "星期二", pinyin: "Xīngqī'èr", th: "วันอังคาร" },
      { cn: "星期三", pinyin: "Xīngqīsān", th: "วันพุธ" },
      { cn: "星期四", pinyin: "Xīngqīsì", th: "วันพฤหัสบดี" },
      { cn: "星期五", pinyin: "Xīngqīwǔ", th: "วันศุกร์" },
      { cn: "星期六", pinyin: "Xīngqīliù", th: "วันเสาร์" },
      { cn: "星期天", pinyin: "Xīngqītiān", th: "วันอาทิตย์" },
      { cn: "几", pinyin: "jǐ", th: "กี่/เท่าไหร่" },
      { cn: "二", pinyin: "èr", th: "สอง" },
      { cn: "三", pinyin: "sān", th: "สาม" },
      { cn: "四", pinyin: "sì", th: "สี่" },
      { cn: "哪儿", pinyin: "nǎr", th: "ที่ไหน" },
      { cn: "那儿", pinyin: "nàr", th: "ที่นั่น" },
      { cn: "我", pinyin: "wǒ", th: "ฉัน" },
      { cn: "回", pinyin: "huí", th: "กลับ" },
      { cn: "学校", pinyin: "xuéxiào", th: "โรงเรียน" },
      { cn: "再见", pinyin: "zàijiàn", th: "ลาก่อน" },
      { cn: "对不起", pinyin: "duìbuqǐ", th: "ขอโทษ" },
      { cn: "没关系", pinyin: "méi guānxi", th: "ไม่เป็นไร" }
    ],
    5: [
      { cn: "这", pinyin: "zhè", th: "นี่" },
      { cn: "是", pinyin: "shì", th: "คือ/เป็น/ใช่" },
      { cn: "老师", pinyin: "lǎoshī", th: "อาจารย์/ครู" },
      { cn: "您", pinyin: "nín", th: "ท่าน (คำสุภาพ)" },
      { cn: "请", pinyin: "qǐng", th: "เชิญ/กรุณา" },
      { cn: "进", pinyin: "jìn", th: "เข้า" },
      { cn: "坐", pinyin: "zuò", th: "นั่ง" },
      { cn: "喝", pinyin: "hē", th: "ดื่ม" },
      { cn: "茶", pinyin: "chá", th: "ชา" },
      { cn: "谢谢", pinyin: "xièxie", th: "ขอบคุณ" },
      { cn: "不客气", pinyin: "bú kèqi", th: "ไม่เป็นไร (ตอบรับการขอบคุณ)" },
      { cn: "客气", pinyin: "kèqi", th: "เกรงใจ/สุภาพ" },
      { cn: "工作", pinyin: "gōngzuò", th: "ทำงาน" },
      { cn: "身体", pinyin: "shēntǐ", th: "ร่างกาย/สุขภาพ" },
      { cn: "身", pinyin: "shēn", th: "ตัว/ร่างกาย" },
      { cn: "十", pinyin: "shí", th: "สิบ" },
      { cn: "日", pinyin: "rì", th: "วัน/พระอาทิตย์" }
    ],
    6: [
      { cn: "请问", pinyin: "qǐngwèn", th: "ขอถามหน่อย" },
      { cn: "问", pinyin: "wèn", th: "ถาม" },
      { cn: "贵姓", pinyin: "guìxìng", th: "นามสกุลของท่าน (สุภาพ)" },
      { cn: "姓", pinyin: "xìng", th: "นามสกุล" },
      { cn: "叫", pinyin: "jiào", th: "ชื่อ/เรียก" },
      { cn: "名字", pinyin: "míngzi", th: "ชื่อ" },
      { cn: "哪", pinyin: "nǎ", th: "ไหน" },
      { cn: "国", pinyin: "guó", th: "ประเทศ" },
      { cn: "人", pinyin: "rén", th: "คน" },
      { cn: "认识", pinyin: "rènshi", th: "รู้จัก" },
      { cn: "高兴", pinyin: "gāoxìng", th: "ดีใจ" },
      { cn: "也", pinyin: "yě", th: "ก็...เหมือนกัน" },
      { cn: "学习", pinyin: "xuéxí", th: "เรียน/ศึกษา" },
      { cn: "什么", pinyin: "shénme", th: "อะไร" },
      { cn: "发音", pinyin: "fāyīn", th: "การออกเสียง" },
      { cn: "汉字", pinyin: "Hànzì", th: "ตัวอักษรจีน" },
      { cn: "书", pinyin: "shū", th: "หนังสือ" },
      { cn: "谁", pinyin: "shéi/shuí", th: "ใคร" },
      { cn: "的", pinyin: "de", th: "ของ" },
      { cn: "那", pinyin: "nà", th: "นั่น/นั้น" },
      { cn: "杂志", pinyin: "zázhì", th: "นิตยสาร" },
      { cn: "中文", pinyin: "Zhōngwén", th: "ภาษาจีน" },
      { cn: "英文", pinyin: "Yīngwén", th: "ภาษาอังกฤษ" },
      { cn: "朋友", pinyin: "péngyou", th: "เพื่อน" }
    ],
    7: [
      { cn: "中午", pinyin: "zhōngwǔ", th: "ตอนเที่ยง" },
      { cn: "吃", pinyin: "chī", th: "กิน" },
      { cn: "饭", pinyin: "fàn", th: "ข้าว" },
      { cn: "食堂", pinyin: "shítáng", th: "โรงอาหาร" },
      { cn: "馒头", pinyin: "mántou", th: "หมั่นโถว" },
      { cn: "要", pinyin: "yào", th: "เอา/ต้องการ" },
      { cn: "个", pinyin: "gè", th: "อัน/ชิ้น (ลักษณนาม)" },
      { cn: "米饭", pinyin: "mǐfàn", th: "ข้าวสวย" },
      { cn: "碗", pinyin: "wǎn", th: "ชาม" },
      { cn: "鸡蛋", pinyin: "jīdàn", th: "ไข่ไก่" },
      { cn: "汤", pinyin: "tāng", th: "ซุป/น้ำแกง" },
      { cn: "啤酒", pinyin: "píjiǔ", th: "เบียร์" },
      { cn: "这些", pinyin: "zhèxiē", th: "พวกนี้" },
      { cn: "一些", pinyin: "yìxiē", th: "บ้าง/เล็กน้อย" },
      { cn: "饺子", pinyin: "jiǎozi", th: "เกี๊ยว" },
      { cn: "包子", pinyin: "bāozi", th: "ซาลาเปา" },
      { cn: "面条儿", pinyin: "miàntiáor", th: "บะหมี่" }
    ],
    8: [
      { cn: "买", pinyin: "mǎi", th: "ซื้อ" },
      { cn: "水果", pinyin: "shuǐguǒ", th: "ผลไม้" },
      { cn: "苹果", pinyin: "píngguǒ", th: "แอปเปิ้ล" },
      { cn: "斤", pinyin: "jīn", th: "ครึ่งกิโลกรัม" },
      { cn: "公斤", pinyin: "gōngjīn", th: "กิโลกรัม" },
      { cn: "多少", pinyin: "duōshao", th: "เท่าไหร่" },
      { cn: "多", pinyin: "duō", th: "มาก" },
      { cn: "少", pinyin: "shǎo", th: "น้อย" },
      { cn: "块（元）", pinyin: "kuài (yuán)", th: "หยวน (หน่วยเงิน)" },
      { cn: "便宜", pinyin: "piányi", th: "ถูก (ราคา)" },
      { cn: "卖", pinyin: "mài", th: "ขาย" },
      { cn: "一共", pinyin: "yígòng", th: "ทั้งหมด" },
      { cn: "给", pinyin: "gěi", th: "ให้" },
      { cn: "找", pinyin: "zhǎo", th: "ทอนเงิน" }
    ],
    9: [
      { cn: "下午", pinyin: "xiàwǔ", th: "ตอนบ่าย" },
      { cn: "上午", pinyin: "shàngwǔ", th: "ตอนเช้า" },
      { cn: "图书馆", pinyin: "túshūguǎn", th: "ห้องสมุด" },
      { cn: "换", pinyin: "huàn", th: "แลก (เช่น แลกเงิน)" },
      { cn: "小姐", pinyin: "xiǎojiě", th: "คุณผู้หญิง/นางสาว" },
      { cn: "营业员", pinyin: "yíngyèyuán", th: "พนักงานขาย" },
      { cn: "人民币", pinyin: "rénmínbì", th: "เงินสกุลจีน" },
      { cn: "美元", pinyin: "měiyuán", th: "ดอลลาร์สหรัฐ" },
      { cn: "等", pinyin: "děng", th: "รอ" },
      { cn: "先生", pinyin: "xiānsheng", th: "คุณผู้ชาย" },
      { cn: "数", pinyin: "shǔ", th: "นับ" }
    ],
    10: [
      { cn: "办公室", pinyin: "bàngōngshì", th: "ที่ทำงาน/ออฟฟิศ" },
      { cn: "在", pinyin: "zài", th: "อยู่ที่" },
      { cn: "家", pinyin: "jiā", th: "บ้าน" },
      { cn: "住", pinyin: "zhù", th: "อาศัยอยู่" },
      { cn: "号", pinyin: "hào", th: "เลขที่/เบอร์" },
      { cn: "楼", pinyin: "lóu", th: "ตึก/ชั้น" },
      { cn: "房间", pinyin: "fángjiān", th: "ห้อง" },
      { cn: "知道", pinyin: "zhīdào", th: "รู้/ทราบ" },
      { cn: "电话", pinyin: "diànhuà", th: "โทรศัพท์" },
      { cn: "手机", pinyin: "shǒujī", th: "มือถือ" }
    ],
    11: [
      { cn: "秘书", pinyin: "mìshū", th: "เลขานุการ" },
      { cn: "先", pinyin: "xiān", th: "ก่อน" },
      { cn: "介绍", pinyin: "jièshào", th: "แนะนำ" },
      { cn: "校长", pinyin: "xiàozhǎng", th: "อธิการบดี/ครูใหญ่" },
      { cn: "位", pinyin: "wèi", th: "ท่าน (ลักษณนามคน)" },
      { cn: "教授", pinyin: "jiàoshòu", th: "ศาสตราจารย์" },
      { cn: "欢迎", pinyin: "huānyíng", th: "ยินดีต้อนรับ" },
      { cn: "留学生", pinyin: "liúxuéshēng", th: "นักเรียนต่างชาติ" },
      { cn: "我们", pinyin: "wǒmen", th: "เรา/พวกเรา" },
      { cn: "你们", pinyin: "nǐmen", th: "คุณ/พวกคุณ" },
      { cn: "他们", pinyin: "tāmen", th: "เขา/พวกเขา" },
      { cn: "学生", pinyin: "xuésheng", th: "นักเรียน" }
    ],
    12: [
      { cn: "语言", pinyin: "yǔyán", th: "ภาษา" },
      { cn: "大学", pinyin: "dàxué", th: "มหาวิทยาลัย" },
      { cn: "怎么样", pinyin: "zěnmeyàng", th: "เป็นยังไงบ้าง" },
      { cn: "觉得", pinyin: "juéde", th: "รู้สึกว่า" },
      { cn: "语法", pinyin: "yǔfǎ", th: "ไวยากรณ์" },
      { cn: "说", pinyin: "shuō", th: "พูด" },
      { cn: "比较", pinyin: "bǐjiào", th: "ค่อนข้าง" },
      { cn: "容易", pinyin: "róngyì", th: "ง่าย" },
      { cn: "但是", pinyin: "dànshì", th: "แต่ว่า" },
      { cn: "新", pinyin: "xīn", th: "ใหม่" },
      { cn: "同学", pinyin: "tóngxué", th: "เพื่อนร่วมชั้น" }
    ],
    13: [
      { cn: "箱子", pinyin: "xiāngzi", th: "กล่อง/กระเป๋าเดินทาง" },
      { cn: "有", pinyin: "yǒu", th: "มี" },
      { cn: "重", pinyin: "zhòng", th: "หนัก" },
      { cn: "黑", pinyin: "hēi", th: "ดำ" },
      { cn: "红", pinyin: "hóng", th: "แดง" },
      { cn: "轻", pinyin: "qīng", th: "เบา" },
      { cn: "旧", pinyin: "jiù", th: "เก่า" },
      { cn: "药", pinyin: "yào", th: "ยา" },
      { cn: "衣服", pinyin: "yīfu", th: "เสื้อผ้า" },
      { cn: "雨伞", pinyin: "yǔsǎn", th: "ร่ม" },
      { cn: "词典", pinyin: "cídiǎn", th: "พจนานุกรม" }
    ],
    14: [
      { cn: "经理", pinyin: "jīnglǐ", th: "ผู้จัดการ" },
      { cn: "好久", pinyin: "hǎojiǔ", th: "นานมาก" },
      { cn: "最近", pinyin: "zuìjìn", th: "ช่วงนี้/เร็วๆ นี้" },
      { cn: "刚", pinyin: "gāng", th: "เพิ่งจะ" },
      { cn: "开学", pinyin: "kāi xué", th: "เปิดเทอม" },
      { cn: "咖啡", pinyin: "kāfēi", th: "กาแฟ" },
      { cn: "车", pinyin: "chē", th: "รถ" },
      { cn: "颜色", pinyin: "yánsè", th: "สี" },
      { cn: "蓝", pinyin: "lán", th: "น้ำเงิน/ฟ้า" }
    ],
    15: [
      { cn: "全", pinyin: "quán", th: "ทั้งหมด" },
      { cn: "照片", pinyin: "zhàopiàn", th: "รูปถ่าย" },
      { cn: "张", pinyin: "zhāng", th: "แผ่น (ลักษณนามรูปภาพ)" },
      { cn: "姐姐", pinyin: "jiějie", th: "พี่สาว" },
      { cn: "做", pinyin: "zuò", th: "ทำ" },
      { cn: "大夫", pinyin: "dàifu", th: "คุณหมอ" },
      { cn: "医院", pinyin: "yīyuàn", th: "โรงพยาบาล" },
      { cn: "公司", pinyin: "gōngsī", th: "บริษัท" },
      { cn: "商店", pinyin: "shāngdiàn", th: "ร้านค้า" },
      { cn: "律师", pinyin: "lǜshī", th: "ทนายความ" },
      { cn: "外国", pinyin: "wàiguó", th: "ต่างประเทศ" }
    ]
  },
 
  2: {
    1: [
    { cn: "现在", pinyin: "xiànzài", th: "ตอนนี้" },
    { cn: "跟", pinyin: "gēn", th: "กับ" },
    { cn: "一起", pinyin: "yìqǐ", th: "ด้วยกัน" },
    { cn: "咱们", pinyin: "zánmen", th: "พวกเรา (รวมผู้ฟัง)" },
    { cn: "走", pinyin: "zǒu", th: "ไป/เดิน" },
    { cn: "常（常）", pinyin: "cháng (cháng)", th: "บ่อยๆ" },
    { cn: "借", pinyin: "jiè", th: "ยืม" },
    { cn: "有时候", pinyin: "yǒu shíhou", th: "บางครั้ง" },
    { cn: "时候", pinyin: "shíhou", th: "เวลา/ตอนที่" },
    { cn: "上网", pinyin: "shàng wǎng", th: "เล่นอินเทอร์เน็ต" },
    { cn: "网", pinyin: "wǎng", th: "เน็ต/ตาข่าย" },
    { cn: "查", pinyin: "chá", th: "ตรวจสอบ/ค้นหา" },
    { cn: "资料", pinyin: "zīliào", th: "ข้อมูล" },
    { cn: "总（是）", pinyin: "zǒng (shì)", th: "มักจะ/เสมอ" },
    { cn: "宿舍", pinyin: "sùshè", th: "หอพัก" },
    { cn: "安静", pinyin: "ānjìng", th: "เงียบสงบ" },
    { cn: "晚上", pinyin: "wǎnshang", th: "ตอนเย็น/กลางคืน" },
    { cn: "复习", pinyin: "fùxí", th: "ทบทวน" },
    { cn: "课文", pinyin: "kèwén", th: "บทเรียน" },
    { cn: "预习", pinyin: "yùxí", th: "เตรียมบทเรียนล่วงหน้า" },
    { cn: "生词", pinyin: "shēngcí", th: "คำศัพท์ใหม่" },
    { cn: "或者", pinyin: "huòzhě", th: "หรือ (ใช้ในประโยคบอกเล่า)" },
    { cn: "练习", pinyin: "liànxí", th: "แบบฝึกหัด/ฝึกฝน" },
    { cn: "聊天儿", pinyin: "liáo tiānr", th: "พูดคุย/เม้าท์มอย" },
    { cn: "发", pinyin: "fā", th: "ส่ง (ข้อความ/อีเมล)" },
    { cn: "微信", pinyin: "wēixìn", th: "วีแชท (WeChat)" },
    { cn: "收发", pinyin: "shōufā", th: "รับและส่ง" },
    { cn: "收", pinyin: "shōu", th: "รับ" },
    { cn: "邮件", pinyin: "yóujiàn", th: "จดหมาย/อีเมล" },
    { cn: "电影", pinyin: "diànyǐng", th: "ภาพยนตร์" },
    { cn: "电视剧", pinyin: "diànshìjù", th: "ละครโทรทัศน์" },
    { cn: "电视", pinyin: "diànshì", th: "โทรทัศน์" },
    { cn: "休息", pinyin: "xiūxi", th: "พักผ่อน" },
    { cn: "公园", pinyin: "gōngyuán", th: "สวนสาธารณะ" },
    { cn: "超市", pinyin: "chāoshì", th: "ซูเปอร์มาร์เก็ต" },
    { cn: "东西", pinyin: "dōngxi", th: "สิ่งของ" }
  ],

  // Unit 2 (第十七课)
  2: [
    { cn: "在", pinyin: "zài", th: "กำลัง...อยู่ / อยู่ที่" },
    { cn: "出来", pinyin: "chūlai", th: "ออกมา" },
    { cn: "来", pinyin: "lái", th: "มา" },
    { cn: "正在", pinyin: "zhèngzài", th: "กำลัง...อยู่" },
    { cn: "音乐", pinyin: "yīnyuè", th: "ดนตรี" },
    { cn: "没有", pinyin: "méiyǒu", th: "ไม่ได้รับ/ไม่มี" },
    { cn: "正", pinyin: "zhèng", th: "กำลัง...พอดี" },
    { cn: "录音", pinyin: "lùyīn", th: "บันทึกเสียง" },
    { cn: "事儿", pinyin: "shìr", th: "ธุระ/เรื่องราว" },
    { cn: "书店", pinyin: "shūdiàn", th: "ร้านหนังสือ" },
    { cn: "想", pinyin: "xiǎng", th: "คิด/อยากจะ" },
    { cn: "汉英", pinyin: "Hàn-Yīng", th: "จีน-อังกฤษ" },
    { cn: "坐", pinyin: "zuò", th: "นั่ง/โดยสาร" },
    { cn: "挤", pinyin: "jǐ", th: "เบียดเสียด/แน่น" },
    { cn: "骑", pinyin: "qí", th: "ขี่ (จักรยาน/ม้า)" },
    { cn: "行", pinyin: "xíng", th: "ตกลง/ได้" },
    { cn: "学期", pinyin: "xuéqī", th: "ภาคเรียน" },
    { cn: "门", pinyin: "mén", th: "วิชา (ลักษณนาม) / ประตู" },
    { cn: "课", pinyin: "kè", th: "บทเรียน/วิชา" },
    { cn: "综合", pinyin: "zōnghé", th: "รวม/สหวิทยาการ" },
    { cn: "口语", pinyin: "kǒuyǔ", th: "การพูด" },
    { cn: "听力", pinyin: "tīnglì", th: "การฟัง" },
    { cn: "阅读", pinyin: "yuèdú", th: "การอ่าน" },
    { cn: "文化", pinyin: "wénhuà", th: "วัฒนธรรม" },
    { cn: "体育", pinyin: "tǐyù", th: "พลศึกษา" },
    { cn: "教", pinyin: "jiāo", th: "สอน" }
  ],

  // Unit 3 (第十八课)
  3: [
    { cn: "修", pinyin: "xiū", th: "ซ่อมแซม" },
    { cn: "顺便", pinyin: "shùnbiàn", th: "ถือโอกาส/แวะ" },
    { cn: "替", pinyin: "tì", th: "แทน" },
    { cn: "盒", pinyin: "hé", th: "กล่อง" },
    { cn: "曲别针", pinyin: "qūbiézhēn", th: "ลวดเสียบกระดาษ" },
    { cn: "拿", pinyin: "ná", th: "หยิบ/ถือ" },
    { cn: "不用", pinyin: "búyòng", th: "ไม่ต้อง" },
    { cn: "用", pinyin: "yòng", th: "ใช้" },
    { cn: "旅行", pinyin: "lǚxíng", th: "ท่องเที่ยว" },
    { cn: "代表", pinyin: "dàibiǎo", th: "ตัวแทน" },
    { cn: "团", pinyin: "tuán", th: "คณะ/กลุ่ม" },
    { cn: "参观", pinyin: "cānguān", th: "เยี่ยมชม" },
    { cn: "当", pinyin: "dāng", th: "เป็น/ทำหน้าที่เป็น" },
    { cn: "翻译", pinyin: "fānyì", th: "แปล/ล่าม" },
    { cn: "飞机", pinyin: "fēijī", th: "เครื่องบิน" },
    { cn: "飞", pinyin: "fēi", th: "บิน" },
    { cn: "火车", pinyin: "huǒchē", th: "รถไฟ" },
    { cn: "回来", pinyin: "huílai", th: "กลับมา" },
    { cn: "帮忙", pinyin: "bāng máng", th: "ช่วยเหลือ" },
    { cn: "帮", pinyin: "bāng", th: "ช่วย" },
    { cn: "浇", pinyin: "jiāo", th: "รดน้ำ" },
    { cn: "花", pinyin: "huā", th: "ดอกไม้" },
    { cn: "没问题", pinyin: "méi wèntí", th: "ไม่มีปัญหา" },
    { cn: "问题", pinyin: "wèntí", th: "คำถาม/ปัญหา" }
  ],

  // Unit 4 (第十九课)
  4: [
    { cn: "光临", pinyin: "guānglín", th: "มาเยือน/ยินดีต้อนรับ" },
    { cn: "羽绒服", pinyin: "yǔróngfú", th: "เสื้อกันหนาวขนเป็ด" },
    { cn: "又……又……", pinyin: "yòu……yòu……", th: "ทั้ง...และ..." },
    { cn: "好看", pinyin: "hǎokàn", th: "สวย/ดูดี" },
    { cn: "一点儿", pinyin: "yìdiǎnr", th: "นิดหน่อย" },
    { cn: "长", pinyin: "cháng", th: "ยาว" },
    { cn: "短", pinyin: "duǎn", th: "สั้น" },
    { cn: "深", pinyin: "shēn", th: "ลึก/เข้ม (สี)" },
    { cn: "浅", pinyin: "qiǎn", th: "ตื้น/อ่อน (สี)" },
    { cn: "试", pinyin: "shì", th: "ลอง" },
    { cn: "可以", pinyin: "kěyǐ", th: "ได้/สามารถ" },
    { cn: "当然", pinyin: "dāngrán", th: "แน่นอน" },
    { cn: "肥", pinyin: "féi", th: "หลวม/อ้วน" },
    { cn: "胖", pinyin: "pàng", th: "อ้วน" },
    { cn: "瘦", pinyin: "shòu", th: "ผอม/แคบ" },
    { cn: "合适", pinyin: "héshì", th: "เหมาะสม/พอดี" },
    { cn: "种", pinyin: "zhǒng", th: "ชนิด/ประเภท" },
    { cn: "打折", pinyin: "dǎ zhé", th: "ลดราคา" }
  ],

  // Unit 5 (第二十课)
  5: [
    { cn: "年", pinyin: "nián", th: "ปี" },
    { cn: "今年", pinyin: "jīnnián", th: "ปีนี้" },
    { cn: "明年", pinyin: "míngnián", th: "ปีหน้า" },
    { cn: "后年", pinyin: "hòunián", th: "ปีมะรืน" },
    { cn: "去年", pinyin: "qùnián", th: "ปีที่แล้ว" },
    { cn: "毕业", pinyin: "bì yè", th: "เรียนจบ" },
    { cn: "多", pinyin: "duō", th: "แค่ไหน/มาก" },
    { cn: "多大", pinyin: "duō dà", th: "อายุเท่าไหร่" },
    { cn: "岁", pinyin: "suì", th: "ปี (อายุ)" },
    { cn: "属", pinyin: "shǔ", th: "เกิดปีนักษัตร..." },
    { cn: "狗", pinyin: "gǒu", th: "สุนัข" },
    { cn: "猪", pinyin: "zhū", th: "หมู" },
    { cn: "生日", pinyin: "shēngrì", th: "วันเกิด" },
    { cn: "月", pinyin: "yuè", th: "เดือน" },
    { cn: "号", pinyin: "hào", th: "วันที่" },
    { cn: "正好", pinyin: "zhènghǎo", th: "พอดี" },
    { cn: "打算", pinyin: "dǎsuàn", th: "วางแผน/ตั้งใจจะ" },
    { cn: "过", pinyin: "過", th: "ฉลอง/ผ่าน" },
    { cn: "准备", pinyin: "zhǔnbèi", th: "เตรียมตัว" },
    { cn: "举行", pinyin: "jǔxíng", th: "จัดงาน" },
    { cn: "晚会", pinyin: "wǎnhuì", th: "งานเลี้ยงเย็น" },
    { cn: "參加", pinyin: "cānjiā", th: "เข้าร่วม" },
    { cn: "时间", pinyin: "shíjiān", th: "เวลา" },
    { cn: "点（钟）", pinyin: "diǎn (zhōng)", th: "โมง/นาฬิกา" },
    { cn: "就", pinyin: "jiù", th: "ก็" },
    { cn: "一定", pinyin: "yídìng", th: "แน่นอน" },
    { cn: "祝", pinyin: "zhù", th: "ขอให้" },
    { cn: "快乐", pinyin: "kuàilè", th: "มีความสุข" },
    { cn: "祝你生日快乐", pinyin: "zhù nǐ shēngrì kuàilè", th: "สุขสันต์วันเกิด" }
  ],

  // Unit 6 (第二十一课)
  6: [
    { cn: "每", pinyin: "měi", th: "ทุกๆ" },
    { cn: "早上", pinyin: "zǎoshang", th: "ตอนเช้า" },
    { cn: "半", pinyin: "bàn", th: "ครึ่ง" },
    { cn: "起床", pinyin: "qǐ chuáng", th: "ตื่นนอน" },
    { cn: "起", pinyin: "qǐ", th: "ลุกขึ้น" },
    { cn: "床", pinyin: "chuáng", th: "เตียง" },
    { cn: "早饭", pinyin: "zǎofàn", th: "อาหารเช้า" },
    { cn: "午饭", pinyin: "wǔfàn", th: "อาหารกลางวัน" },
    { cn: "晚饭", pinyin: "wǎnfàn", th: "อาหารเย็น" },
    { cn: "差", pinyin: "chà", th: "ขาดอีก/แย่" },
    { cn: "分（钟）", pinyin: "fēn (zhōng)", th: "นาที" },
    { cn: "教室", pinyin: "jiàoshì", th: "ห้องเรียน" },
    { cn: "上课", pinyin: "shàng kè", th: "เข้าเรียน" },
    { cn: "节", pinyin: "jié", th: "คาบ (ลักษณนาม)" },
    { cn: "下课", pinyin: "xià kè", th: "เลิกเรียน" },
    { cn: "以后", pinyin: "yǐhòu", th: "หลังจาก" },
    { cn: "操场", pinyin: "cāochǎng", th: "สนามหญ้า/สนามกีฬา" },
    { cn: "锻炼", pinyin: "duànliàn", th: "ฝึกฝน/ออกกำลังกาย" },
    { cn: "洗澡", pinyin: "xǐ zǎo", th: "อาบน้ำ" },
    { cn: "洗", pinyin: "xǐ", th: "ล้าง/ซัก" },
    { cn: "然后", pinyin: "ránhòu", th: "หลังจากนั้น" },
    { cn: "睡觉", pinyin: "shuì jiào", th: "นอนหลับ" },
    { cn: "们", pinyin: "men", th: "พวก... (พหูพจน์)" },
    { cn: "爬", pinyin: "pá", th: "ปีน/คลาน" },
    { cn: "山", pinyin: "shān", th: "ภูเขา" },
    { cn: "年级", pinyin: "niánjí", th: "ชั้นปี" },
    { cn: "出发", pinyin: "chūfā", th: "ออกเดินทาง" },
    { cn: "前", pinyin: "qián", th: "หน้า/ก่อน" },
    { cn: "集合", pinyin: "jíhé", th: "รวมตัว" },
    { cn: "上车", pinyin: "shàng chē", th: "ขึ้นรถ" },
    { cn: "下车", pinyin: "xià chē", th: "ลงรถ" },
    { cn: "刻", pinyin: "kè", th: "15 นาที" },
    { cn: "准时", pinyin: "zhǔnshí", th: "ตรงเวลา" },
    { cn: "带", pinyin: "dài", th: "พก/พา/นำ" }
  ],

  // Unit 7 (第二十二课)
  7: [
    { cn: "大家", pinyin: "dàjiā", th: "ทุกคน" },
    { cn: "谈", pinyin: "tán", th: "คุย/สนทนา" },
    { cn: "自己", pinyin: "zìjǐ", th: "ตัวเอง" },
    { cn: "爱好", pinyin: "àihào", th: "งานอดิเรก" },
    { cn: "让", pinyin: "ràng", th: "ให้/อนุญาต" },
    { cn: "叫", pinyin: "jiào", th: "เรียก/สั่งให้" },
    { cn: "京剧", pinyin: "jīngjù", th: "งิ้วปักกิ่ง" },
    { cn: "喜欢", pinyin: "xǐhuan", th: "ชอบ" },
    { cn: "非常", pinyin: "fēicháng", th: "อย่างยิ่ง" },
    { cn: "唱", pinyin: "chàng", th: "ร้องเพลง" },
    { cn: "玩儿", pinyin: "wánr", th: "เล่น" },
    { cn: "电脑", pinyin: "diànnǎo", th: "คอมพิวเตอร์" },
    { cn: "游戏", pinyin: "yóuxì", th: "เกม" },
    { cn: "感到", pinyin: "gǎndào", th: "รู้สึก" },
    { cn: "心情", pinyin: "xīnqíng", th: "อารมณ์" },
    { cn: "愉快", pinyin: "yúkuài", th: "รื่นเริง/เป็นสุข" },
    { cn: "业余", pinyin: "yèyú", th: "เวลาว่าง" },
    { cn: "以前", pinyin: "yǐqián", th: "เมื่อก่อน" },
    { cn: "就", pinyin: "jiù", th: "ก็" },
    { cn: "对", pinyin: "duì", th: "ต่อ/กับ" },
    { cn: "书法", pinyin: "shūfǎ", th: "การเขียนพู่กันจีน" },
    { cn: "特别", pinyin: "tèbié", th: "เป็นพิเศษ" },
    { cn: "感兴趣", pinyin: "gǎn xìngqù", th: "รู้สึกสนใจ" },
    { cn: "兴趣", pinyin: "xìngqù", th: "ความสนใจ" },
    { cn: "派", pinyin: "pài", th: "ส่งไป" },
    { cn: "画", pinyin: "huà", th: "วาด" },
    { cn: "画儿", pinyin: "huàr", th: "รูปวาด" }
  ],

  // Unit 8 (第二十三课)
  8: [
    { cn: "……边", pinyin: "……biān", th: "ด้าน..." },
    { cn: "东边", pinyin: "dōngbiān", th: "ทิศตะวันออก" },
    { cn: "西边", pinyin: "xībiān", th: "ทิศตะวันตก" },
    { cn: "南边", pinyin: "nánbiān", th: "ทิศใต้" },
    { cn: "北边", pinyin: "běibiān", th: "ทิศเหนือ" },
    { cn: "前边", pinyin: "qiánbiān", th: "ข้างหน้า" },
    { cn: "后边", pinyin: "hòubiān", th: "ข้างหลัง" },
    { cn: "左边", pinyin: "zuǒbiān", th: "ข้างซ้าย" },
    { cn: "右边", pinyin: "yòubiān", th: "ข้างขวา" },
    { cn: "里边", pinyin: "lǐbiān", th: "ข้างใน" },
    { cn: "外边", pinyin: "wàibiān", th: "ข้างนอก" },
    { cn: "上边", pinyin: "shàngbiān", th: "ข้างบน" },
    { cn: "下边", pinyin: "xiàbiān", th: "ข้างล่าง" },
    { cn: "离", pinyin: "lí", th: "ห่างจาก" },
    { cn: "远", pinyin: "yuǎn", th: "ไกล" },
    { cn: "近", pinyin: "jìn", th: "ใกล้" },
    { cn: "地方", pinyin: "dìfang", th: "สถานที่" },
    { cn: "足球场", pinyin: "zúqiúchǎng", th: "สนามฟุตบอล" },
    { cn: "足球", pinyin: "zúqiú", th: "ฟุตบอล" },
    { cn: "劳驾", pinyin: "láo jià", th: "ขอโทษนะ/ขอรบกวนหน่อย" },
    { cn: "打听", pinyin: "dǎting", th: "สอบถาม" },
    { cn: "博物馆", pinyin: "bówùguǎn", th: "พิพิธภัณฑ์" },
    { cn: "和平", pinyin: "hépíng", th: "สันติภาพ" },
    { cn: "广场", pinyin: "guǎngchǎng", th: "จตุรัส/ลานกว้าง" },
    { cn: "中间", pinyin: "zhōngjiān", th: "ตรงกลาง" },
    { cn: "从", pinyin: "cóng", th: "จาก" },
    { cn: "到", pinyin: "dào", th: "ถึง" },
    { cn: "米", pinyin: "mǐ", th: "เมตร" },
    { cn: "一直", pinyin: "yīzhí", th: "ตรงไปตลอด" },
    { cn: "往", pinyin: "wǎng", th: "ไปทาง" },
    { cn: "红绿灯", pinyin: "hónglǜdēng", th: "ไฟจราจร" },
    { cn: "绿", pinyin: "lǜ", th: "สีเขียว" },
    { cn: "灯", pinyin: "dēng", th: "ไฟ" },
    { cn: "左", pinyin: "zuǒ", th: "ซ้าย" },
    { cn: "右", pinyin: "yòu", th: "ขวา" },
    { cn: "拐", pinyin: "guǎi", th: "เลี้ยว" },
    { cn: "马路", pinyin: "mǎlù", th: "ถนน" },
    { cn: "路", pinyin: "lù", th: "ทาง" },
    { cn: "座", pinyin: "zuò", th: "หลัง/อาคาร (ลักษณนาม)" },
    { cn: "白色", pinyin: "báisè", th: "สีขาว" }
  ],
 9: [
    { cn: "会", pinyin: "huì", th: "เป็น/สามารถ" },
    { cn: "打", pinyin: "dǎ", th: "ตี/เล่น" },
    { cn: "太极拳", pinyin: "tàijíquán", th: "มวยไทเก๊ก" },
    { cn: "听说", pinyin: "tīngshuō", th: "ได้ยินว่า" },
    { cn: "下", pinyin: "xià", th: "หน้า (ถัดไป) / ลง" },
    { cn: "报名", pinyin: "bào míng", th: "สมัคร" },
    { cn: "开始", pinyin: "kāishǐ", th: "เริ่ม" },
    { cn: "能", pinyin: "néng", th: "สามารถ" },
    { cn: "再", pinyin: "zài", th: "อีกครั้ง" },
    { cn: "遍", pinyin: "biàn", th: "รอบ/ครั้ง (ตั้งแต่ต้นจนจบ)" },
    { cn: "懂", pinyin: "dǒng", th: "เข้าใจ" },
    { cn: "意思", pinyin: "yìsi", th: "ความหมาย" },
    { cn: "次", pinyin: "cì", th: "ครั้ง" },
    { cn: "小时", pinyin: "xiǎoshí", th: "ชั่วโมง" },
    { cn: "请假", pinyin: "qǐng jià", th: "ลาหยุด" },
    { cn: "舒服", pinyin: "shūfu", th: "สบาย" },
    { cn: "头疼", pinyin: "tóu téng", th: "ปวดหัว" },
    { cn: "头", pinyin: "tóu", th: "หัว" },
    { cn: "疼", pinyin: "téng", th: "ปวด/เจ็บ" },
    { cn: "发烧", pinyin: "fā shāo", th: "มีไข้" },
    { cn: "咳嗽", pinyin: "késou", th: "ไอ" },
    { cn: "可能", pinyin: "kěnéng", th: "อาจจะ" },
    { cn: "感冒", pinyin: "gǎnmào", th: "เป็นหวัด" },
    { cn: "看病", pinyin: "kàn bìng", th: "ไปหาหมอ" },
    { cn: "病", pinyin: "bìng", th: "ป่วย" }
  ],
  10: [
    { cn: "电视台", pinyin: "diànshìtái", th: "สถานีโทรทัศน์" },
    { cn: "台", pinyin: "tái", th: "เครื่อง/สถานี" },
    { cn: "表演", pinyin: "biǎoyǎn", th: "แสดง" },
    { cn: "节目", pinyin: "jiémù", th: "รายการ" },
    { cn: "愿意", pinyin: "yuànyì", th: "สมัครใจ/ยินยอม" },
    { cn: "为什么", pinyin: "wèi shénme", th: "ทำไม" },
    { cn: "得", pinyin: "de", th: "ได้... (ใช้หลัง V. แสดงระดับ)" },
    { cn: "不错", pinyin: "búcuò", th: "ไม่เลว/ดี" },
    { cn: "错", pinyin: "cuò", th: "ผิด" },
    { cn: "进步", pinyin: "jìnbù", th: "ก้าวหน้า" },
    { cn: "水平", pinyin: "shuǐpíng", th: "ระดับ" },
    { cn: "提高", pinyin: "tígāo", th: "พัฒนา/ยกระดับ" },
    { cn: "快", pinyin: "kuài", th: "เร็ว" },
    { cn: "哪里", pinyin: "nǎli", th: "ที่ไหน (ใช้ถล่มตัวเวลาคนชม)" },
    { cn: "准", pinyin: "zhǔน", th: "แม่นยำ/เป๊ะ" },
    { cn: "流利", pinyin: "liúlì", th: "คล่องแคล่ว" },
    { cn: "这么", pinyin: "zhème", th: "ขนาดนี้/อย่างนี้" },
    { cn: "那么", pinyin: "nàme", th: "ขนาดนั้น/อย่างนั้น" },
    { cn: "努力", pinyin: "nǔlì", th: "ขยัน/พยายาม" },
    { cn: "认真", pinyin: "rènzhēn", th: "จริงจัง" },
    { cn: "看", pinyin: "kàn", th: "ดู/มอง" },
    { cn: "为", pinyin: "wèi", th: "เพื่อ" },
    { cn: "早", pinyin: "zǎo", th: "เร็ว/เช้า" },
    { cn: "运动", pinyin: "yùndòng", th: "ออกกำลังกาย" },
    { cn: "跑步", pinyin: "pǎo bù", th: "วิ่งจ็อกกิ้ง" },
    { cn: "跑", pinyin: "pǎo", th: "วิ่ง" },
    { cn: "篮球", pinyin: "lánqiú", th: "บาสเกตบอล" },
    { cn: "球", pinyin: "qiú", th: "ลูกบอล" },
    { cn: "刚才", pinyin: "gāngcái", th: "เมื่อกี้" },
    { cn: "可以", pinyin: "kěyǐ", th: "ได้/ใช้ได้" },
    { cn: "坚持", pinyin: "jiānchí", th: "ยืนหยัด/ทำต่อไป" },
    { cn: "เพราะว่า", pinyin: "yīnwèi", th: "เพราะว่า" },
    { cn: "晚", pinyin: "wǎn", th: "สาย/ช้า/ดึก" }
  ]
 },
  3: {
    1: [
      { cn: "喂", pinyin: "wèi", th: "ฮัลโหล" },
      { cn: "阿姨", pinyin: "āyí", th: "น้า, อา (ผู้หญิง), คุณป้า" },
      { cn: "了", pinyin: "le", th: "แล้ว" },
      { cn: "中学", pinyin: "zhōngxué", th: "โรงเรียนมัธยม" },
      { cn: "出国", pinyin: "chū guó", th: "ไปต่างประเทศ" },
      { cn: "出", pinyin: "chū", th: "ออก" },
      { cn: "打（电话）", pinyin: "dǎ (diànhuà)", th: "โทร (โทรศัพท์)" },
      { cn: "关机", pinyin: "guānjī", th: "ปิดเครื่อง" },
      { cn: "关", pinyin: "guān", th: "ปิด" },
      { cn: "饿", pinyin: "è", th: "หิว" },
      { cn: "对了", pinyin: "duìle", th: "จริงด้วย, เออใช่" },
      { cn: "忘", pinyin: "wàng", th: "ลืม" },
      { cn: "开机", pinyin: "kāi jī", th: "เปิดเครื่อง" },
      { cn: "开", pinyin: "kāi", th: "เปิด" },
      { cn: "又", pinyin: "yòu", th: "อีกแล้ว" },
      { cn: "响", pinyin: "xiǎng", th: "ดัง (เสียง)" },
      { cn: "接", pinyin: "jiē", th: "รับ (สาย/คน)" },
      { cn: "踢", pinyin: "tī", th: "เตะ" },
      { cn: "比赛", pinyin: "bǐsài", th: "การแข่งขัน" },
      { cn: "队", pinyin: "duì", th: "ทีม" },
      { cn: "输", pinyin: "shū", th: "แพ้" },
      { cn: "赢", pinyin: "yíng", th: "ชนะ" },
      { cn: "比", pinyin: "bǐ", th: "ต่อ (บอกคะแนน)" },
      { cn: "祝贺", pinyin: "zhùhè", th: "แสดงความยินดี" },
      { cn: "哎", pinyin: "āi", th: "คำอุทาน (ประหลาดใจ)" },
      { cn: "上", pinyin: "shàng", th: "เข้าเรียน/เข้าหลักสูตร" },
      { cn: "托福", pinyin: "tuōfú", th: "โทเฟล (TOEFL)" },
      { cn: "已经", pinyin: "yǐjīng", th: "เรียบร้อยแล้ว" },
      { cn: "考", pinyin: "kǎo", th: "สอบ" },
      { cn: "陪", pinyin: "péi", th: "อยู่เป็นเพื่อน" }
    ],
    2: [
      { cn: "病人", pinyin: "bìngrén", th: "คนไข้" },
      { cn: "肚子", pinyin: "dùzi", th: "ท้อง" },
      { cn: "厉害", pinyin: "lìhai", th: "รุนแรง, เก่ง" },
      { cn: "了", pinyin: "le", th: "แล้ว" },
      { cn: "片", pinyin: "piàn", th: "เม็ด (ลักษณนามยา)" },
      { cn: "拉肚子", pinyin: "lā dùzi", th: "ท้องเสีย" },
      { cn: "拉", pinyin: "lā", th: "ถ่าย (ท้อง)" },
      { cn: "鱼", pinyin: "yú", th: "ปลา" },
      { cn: "牛肉", pinyin: "niúròu", th: "เนื้อวัว" },
      { cn: "化验", pinyin: "huàyàn", th: "ตรวจแล็บ" },
      { cn: "大便", pinyin: "dàbiàn", th: "อุจจาระ" },
      { cn: "小便", pinyin: "xiǎobiàn", th: "ปัสสาวะ" },
      { cn: "检查", pinyin: "jiǎnchá", th: "ตรวจเช็ก" },
      { cn: "结果", pinyin: "jiéguǒ", th: "ผลลัพธ์" },
      { cn: "出来", pinyin: "chūlay", th: "ออกมา" },
      { cn: "得", pinyin: "dé", th: "ป่วยเป็น..." },
      { cn: "肠炎", pinyin: "chángyán", th: "ลำไส้อักเสบ" },
      { cn: "消化", pinyin: "xiāohuà", th: "ย่อยอาหาร" },
      { cn: "开（药）", pinyin: "kāi (yào)", th: "สั่ง (ยา)" },
      { cn: "打针", pinyin: "dǎ zhēn", th: "ฉีดยา" },
      { cn: "后", pinyin: "hòu", th: "หลัง" },
      { cn: "哭", pinyin: "kū", th: "ร้องไห้" },
      { cn: "寂寞", pinyin: "jìmò", th: "เหงา" },
      { cn: "所以", pinyin: "suǒyǐ", th: "ดังนั้น" },
      { cn: "别", pinyin: "bié", th: "อย่า" },
      { cn: "难过", pinyin: "nánguò", th: "เสียใจ" },
      { cn: "礼堂", pinyin: "lǐtáng", th: "หอประชุม" },
      { cn: "舞会", pinyin: "wǔhuì", th: "งานเต้นรำ" },
      { cn: "跳舞", pinyin: "tiào wǔ", th: "เต้นรำ" }
    ],
    3: [
      { cn: "套", pinyin: "tào", th: "ชุด (ลักษณนามบ้าน/ห้อง)" },
      { cn: "房子", pinyin: "fángzi", th: "บ้าน/ห้องชุด" },
      { cn: "满意", pinyin: "mǎnyì", th: "พอใจ" },
      { cn: "有的", pinyin: "yǒude", th: "บางอย่าง/บางอัน" },
      { cn: "周围", pinyin: "zhōuwei", th: "บริเวณรอบๆ" },
      { cn: "环境", pinyin: "huánjìng", th: "สภาพแวดล้อม" },
      { cn: "乱", pinyin: "luàn", th: "รก/วุ่นวาย" },
      { cn: "厨房", pinyin: "chúfáng", th: "ห้องครัว" },
      { cn: "卧室", pinyin: "wòshì", th: "ห้องนอน" },
      { cn: "客厅", pinyin: "kètīng", th: "ห้องรับแขก" },
      { cn: "面积", pinyin: "miànjī", th: "พื้นที่" },
      { cn: "层", pinyin: "céng", th: "ชั้น" },
      { cn: "平（方）米", pinyin: "píng(fāng)mǐ", th: "ตารางเมตร" },
      { cn: "上去", pinyin: "shàngqu", th: "ขึ้นไป" },
      { cn: "阳光", pinyin: "yángguāng", th: "แสงแดด" },
      { cn: "还是", pinyin: "háishi", th: "ดีกว่า/หรือว่า" },
      { cn: "妻子", pinyin: "qīzi", th: "ภรรยา" },
      { cn: "堵车", pinyin: "dǔ chē", th: "รถติด" },
      { cn: "赶", pinyin: "gǎn", th: "รีบไป/เร่ง" },
      { cn: "才", pinyin: "cái", th: "เพิ่งจะ/ถึงจะ" },
      { cn: "要是", pinyin: "yàoshi", th: "ถ้าหาก" },
      { cn: "租", pinyin: "zū", th: "เช่า" },
      { cn: "房租", pinyin: "fángzū", th: "ค่าเช่าบ้าน" },
      { cn: "虽然", pinyin: "suīrán", th: "แม้ว่า" },
      { cn: "真", pinyin: "zhēn", th: "จริง" },
      { cn: "条", pinyin: "tiáo", th: "สาย (ลักษณนามแม่น้ำ/ถนน)" },
      { cn: "河", pinyin: "hé", th: "แม่น้ำ" },
      { cn: "交通", pinyin: "jiāotōng", th: "การคมนาคม" },
      { cn: "方便", pinyin: "fāngbiàn", th: "สะดวกสบาย" },
      { cn: "公共汽车", pinyin: "gōnggòng qìchē", th: "รถเมล์" },
      { cn: "站", pinyin: "zhàn", th: "ป้าย/สถานี" },
      { cn: "车站", pinyin: "chēzhàn", th: "สถานีรถ" }
    ],
    4: [
      { cn: "考试", pinyin: "kǎo shì", th: "สอบ" },
      { cn: "题", pinyin: "tí", th: "ข้อสอบ/โจทย์" },
      { cn: "完", pinyin: "wán", th: "เสร็จ/จบ" },
      { cn: "道", pinyin: "dào", th: "ข้อ (ลักษณนามโจทย์)" },
      { cn: "成绩", pinyin: "chéngjì", th: "คะแนน/ผลการเรียน" },
      { cn: "句子", pinyin: "jùzi", th: "ประโยค" },
      { cn: "看见", pinyin: "kàn jiàn", th: "มองเห็น" },
      { cn: "见", pinyin: "jiàn", th: "เห็น" },
      { cn: "干什么", pinyin: "gàn shénme", th: "ทำอะไร" },
      { cn: "干", pinyin: "gàn", th: "ทำ" },
      { cn: "词", pinyin: "cí", th: "คำศัพท์" },
      { cn: "糟糕", pinyin: "zāogāo", th: "แย่แล้ว/ซวยแล้ว" },
      { cn: "成", pinyin: "chéng", th: "กลายเป็น" },
      { cn: "回信", pinyin: "huí xìn", th: "ตอบจดหมาย" },
      { cn: "故事", pinyin: "gùshi", th: "นิทาน/เรื่องราว" },
      { cn: "有意思", pinyin: "yǒu yìsi", th: "น่าสนใจ/สนุก" },
      { cn: "页", pinyin: "yè", th: "หน้า (กระดาษ)" },
      { cn: "笑", pinyin: "xiào", th: "หัวเราะ/ยิ้ม" },
      { cn: "会话", pinyin: "huìhuà", th: "บทสนทนา" },
      { cn: "念", pinyin: "niàn", th: "อ่านออกเสียง" },
      { cn: "答", pinyin: "dá", th: "ตอบ" },
      { cn: "办法", pinyin: "bànfǎ", th: "วิธีการ" },
      { cn: "合上", pinyin: "héshang", th: "ปิด (สมุด/หนังสือ)" },
      { cn: "上", pinyin: "shang", th: "(เป็นคำเสริมกริยา)" },
      { cn: "打开", pinyin: "dǎ kāi", th: "เปิดออก" },
      { cn: "听见", pinyin: "tīng jiàn", th: "ได้ยิน" },
      { cn: "作业", pinyin: "zuòyè", th: "การบ้าน" },
      { cn: "熟", pinyin: "shú", th: "คล่องแคล่ว/สุก" }
    ],
    5: [
      { cn: "生活", pinyin: "shēnghuó", th: "การใช้ชีวิต" },
      { cn: "差不多", pinyin: "chàbuduō", th: "พอๆ กัน/เกือบจะ" },
      { cn: "习惯", pinyin: "xíguàn", th: "ความเคยชิน/นิสัย" },
      { cn: "不过", pinyin: "búguò", th: "แต่ว่า" },
      { cn: "气候", pinyin: "qìhòu", th: "สภาพอากาศ" },
      { cn: "干燥", pinyin: "gānzào", th: "แห้งแล้ง" },
      { cn: "干净", pinyin: "gānjìng", th: "สะอาด" },
      { cn: "菜", pinyin: "cài", th: "อาหาร/ผัก" },
      { cn: "油腻", pinyin: "yóunì", th: "เลี่ยน/มัน" },
      { cn: "牛奶", pinyin: "niúnǎi", th: "นมวัว" },
      { cn: "课间", pinyin: "kèjiān", th: "ช่วงพักคาบเรียน" },
      { cn: "块", pinyin: "kuài", th: "ชิ้น (ลักษณนาม)" },
      { cn: "点心", pinyin: "diǎnxin", th: "ขนมทานเล่น" },
      { cn: "从来", pinyin: "cónglái", th: "แต่ไหนแต่ไรมา" },
      { cn: "午觉", pinyin: "wǔjiào", th: "นอนกลางวัน" },
      { cn: "游泳", pinyin: "yóu yǒng", th: "ว่ายน้ำ" },
      { cn: "散步", pinyin: "sàn bù", th: "เดินเล่น" },
      { cn: "功课", pinyin: "gōngkè", th: "วิชาที่เรียน/การบ้าน" },
      { cn: "记", pinyin: "jì", th: "จดจำ" },
      { cn: "住", pinyin: "zhù", th: "ไว้/อยู่ (ใช้หลังกริยาเพื่อบอกความคงทน)" },
      { cn: "一般", pinyin: "yìbān", th: "ปกติทั่วไป" },
      { cn: "感谢", pinyin: "gǎnxiè", th: "ขอบคุณ" },
      { cn: "父母", pinyin: "fùmǔ", th: "พ่อแม่" },
      { cn: "机会", pinyin: "jīhuì", th: "โอกาส" },
      { cn: "原来", pinyin: "yuánlái", th: "ที่แท้/แต่เดิม" },
      { cn: "延长", pinyin: "yáncháng", th: "ขยายเวลา" },
      { cn: "练", pinyin: "liàn", th: "ฝึกฝน" },
      { cn: "气功", pinyin: "qìgōng", th: "ชี่กง" },
      { cn: "好", pinyin: "hǎo", th: "ดี" },
      { cn: "不一定", pinyin: "bù yídìng", th: "ไม่แน่นอน" },
      { cn: "钟头", pinyin: "zhōngtóu", th: "ชั่วโมง" },
      { cn: "效果", pinyin: "xiàoguǒ", th: "ผลลัพธ์/ประสิทธิผล" },
      { cn: "挺", pinyin: "tǐng", th: "มาก" },
      { cn: "好处", "pinyin": "hǎochù", th: "ข้อดี" },
      { cn: "坏处", pinyin: "huàichù", th: "ข้อเสีย" },
      { cn: "慢性病", pinyin: "mànxìngbìng", th: "โรคเรื้อรัง" },
      { cn: "高血压", pinyin: "gāoxuèyā", th: "ความดันโลหิตสูง" },
      { cn: "失眠", pinyin: "shī mián", th: "นอนไม่หลับ" }
    ],
    6: [
      { cn: "变化", pinyin: "biànhuà", th: "การเปลี่ยนแปลง" },
      { cn: "变", pinyin: "biàn", th: "เปลี่ยน" },
      { cn: "暑假", pinyin: "shǔjià", th: "ปิดเทอมฤดูร้อน" },
      { cn: "还", pinyin: "hái", th: "ยังคง" },
      { cn: "比", pinyin: "bǐ", th: "กว่า (เปรียบเทียบ)" },
      { cn: "人口", pinyin: "rénkǒu", th: "ประชากร" },
      { cn: "最", pinyin: "zuì", th: "ที่สุด" },
      { cn: "城市", pinyin: "chéngshì", th: "เมือง" },
      { cn: "增加", pinyin: "zēngjiā", th: "เพิ่มขึ้น" },
      { cn: "建筑", pinyin: "jiànzhù", th: "สิ่งก่อสร้าง" },
      { cn: "过去", pinyin: "guòqù", th: "อดีต/แต่ก่อน" },
      { cn: "更", pinyin: "gèng", th: "ยิ่งกว่า" },
      { cn: "漂亮", pinyin: "piàoliang", th: "สวย" },
      { cn: "冬（天）", pinyin: "dōng (tiān)", th: "ฤดูหนาว" },
      { cn: "暖和", pinyin: "nuǎnhuo", th: "อบอุ่น" },
      { cn: "可是", pinyin: "kěshì", th: "แต่ว่า" },
      { cn: "天气", pinyin: "tiānqì", th: "อากาศ" },
      { cn: "预报", pinyin: "yùbào", th: "พยากรณ์" },
      { cn: "气温", pinyin: "qìwēn", th: "อุณหภูมิ" },
      { cn: "高", pinyin: "gāo", th: "สูง" },
      { cn: "度", pinyin: "dù", th: "องศา" },
      { cn: "屋子", pinyin: "wūzi", th: "ห้อง" },
      { cn: "暖气", pinyin: "nuǎnqì", th: "เครื่องทำความร้อน" },
      { cn: "感觉", pinyin: "gǎnjué", th: "รู้สึก" },
      { cn: "家庭", pinyin: "jiātíng", th: "ครอบครัว" },
      { cn: "旅馆", pinyin: "lǚguǎn", th: "โรงแรม" },
      { cn: "饭店", pinyin: "fàndiàn", th: "ร้านอาหาร/โรงแรม" },
      { cn: "迷", pinyin: "mí", th: "แฟนคลับ/หลงใหล" },
      { cn: "光", pinyin: "guāng", th: "เพียงแค่" },
      { cn: "交响乐", pinyin: "jiāoxiǎngyuè", th: "วงซิมโฟนี" },
      { cn: "下载", pinyin: "xiàzài", th: "ดาวน์โหลด" },
      { cn: "首", pinyin: "shǒu", th: "เพลง (ลักษณนาม)" },
      { cn: "也许", pinyin: "yěxǔ", th: "อาจจะ" },
      { cn: "古典", pinyin: "gǔdiǎn", th: "คลาสสิก" },
      { cn: "现代", pinyin: "xiàndài", th: "สมัยใหม่" },
      { cn: "世界", pinyin: "shìjiè", th: "โลก" },
      { cn: "名曲", pinyin: "míngqǔ", th: "เพลงดัง" },
      { cn: "民歌", pinyin: "míngē", th: "เพลงพื้นเมือง" },
      { cn: "流行", pinyin: "liúxíng", th: "ยอดนิยม/ป๊อป" },
      { cn: "歌曲", pinyin: "gēqǔ", th: "บทเพลง" },
      { cn: "年轻", pinyin: "niánqīng", th: "อายุน้อย/วัยรุ่น" },
      { cn: "歌词", pinyin: "gēcí", th: "เนื้อเพลง" },
      { cn: "有些", pinyin: "yǒuxiē", th: "บางอัน/บางคน" },
      { cn: "遥远", pinyin: "yáoyuǎn", th: "ไกลโพ้น" }
    ],
    7: [
      { cn: "国家", pinyin: "guójiā", th: "ประเทศ" },
      { cn: "一样", pinyin: "yíyàng", th: "เหมือนกัน" },
      { cn: "时差", pinyin: "shíchā", th: "ความต่างของเวลา" },
      { cn: "夜", pinyin: "yè", th: "กลางคืน" },
      { cn: "季节", pinyin: "jìjié", th: "ฤดูกาล" },
      { cn: "季", pinyin: "jì", th: "ฤดู" },
      { cn: "春（天）", pinyin: "chūn (tiān)", th: "ฤดูใบไม้ผลิ" },
      { cn: "夏（天）", pinyin: "xià (tiān)", th: "ฤดูร้อน" },
      { cn: "秋（天）", pinyin: "qiū (tiān)", th: "ฤดูใบไม้ร่วง" },
      { cn: "热", pinyin: "rè", th: "ร้อน" },
      { cn: "冷", pinyin: "lěng", th: "หนาว" },
      { cn: "刮风", pinyin: "guā fēng", th: "ลมพัด" },
      { cn: "风", pinyin: "fēng", th: "ลม" },
      { cn: "下雪", pinyin: "xià xuě", th: "หิมะตก" },
      { cn: "下", pinyin: "xià", th: "ตก (ฝน/หิมะ)" },
      { cn: "雪", pinyin: "xuě", th: "หิมะ" },
      { cn: "下雨", pinyin: "xià yǔ", th: "ฝนตก" },
      { cn: "不但……而且……", pinyin: "búdàn……érqiě……", th: "ไม่เพียงแต่...แต่ยัง..." },
      { cn: "分", pinyin: "fēn", th: "คะแนน" },
      { cn: "得", pinyin: "dé", th: "ได้รับ (คะแนน)" },
      { cn: "听写", pinyin: "tīngxiě", th: "เขียนตามคำบอก" },
      { cn: "周末", pinyin: "zhōumò", th: "สุดสัปดาห์" },
      { cn: "出去", pinyin: "chūqu", th: "ออกไป" },
      { cn: "历史", pinyin: "lìshǐ", th: "ประวัติศาสตร์" },
      { cn: "产生", pinyin: "chǎnshēng", th: "เกิด (ความรู้สึก/ผลกระทบ)" },
      { cn: "画册", pinyin: "huàcè", th: "สมุดภาพ" },
      { cn: "研究", pinyin: "yánjiū", th: "วิจัย" },
      { cn: "只是", pinyin: "zhǐshì", th: "แค่เพียงว่า" },
      { cn: "老", pinyin: "lǎo", th: "แก่/เก่า" },
      { cn: "改革", pinyin: "gǎigé", th: "ปฏิรูป" },
      { cn: "开放", pinyin: "kāifàng", th: "เปิด (นโยบาย)" },
      { cn: "一切", pinyin: "yíqiè", th: "ทุกอย่าง" }
    ],
    8: [
      { cn: "爱", pinyin: "ài", th: "รัก/ชอบ" },
      { cn: "滑冰", pinyin: "huá bīng", th: "สเก็ตน้ำแข็ง" },
      { cn: "滑雪", pinyin: "huá xuě", th: "เล่นสกี" },
      { cn: "家乡", pinyin: "jiāxiāng", th: "บ้านเกิด" },
      { cn: "水", pinyin: "shuǐ", th: "น้ำ" },
      { cn: "有名", pinyin: "yǒumíng", th: "มีชื่อเสียง" },
      { cn: "风景", pinyin: "fēngjǐng", th: "วิวทิวทัศน์" },
      { cn: "区", pinyin: "qū", th: "เขต/บริเวณ" },
      { cn: "旅游", pinyin: "lǚyóu", th: "ท่องเที่ยว" },
      { cn: "尤其", pinyin: "yóuqí", th: "โดยเฉพาะอย่างยิ่ง" },
      { cn: "涼快", pinyin: "liángkuai", th: "เย็นสบาย" },
      { cn: "避暑", pinyin: "bì shǔ", th: "ตากอากาศ" },
      { cn: "人家", pinyin: "rénjiā", th: "คนในครอบครัว" },
      { cn: "靠", pinyin: "kào", th: "พึ่งพา/อาศัย" },
      { cn: "经营", pinyin: "jīngyíng", th: "บริหาร/จัดการ" },
      { cn: "发财", pinyin: "fā cái", th: "ร่ำรวย" },
      { cn: "树叶", pinyin: "shùyè", th: "ใบไม้" },
      { cn: "树", pinyin: "shù", th: "ต้นไม้" },
      { cn: "叶", pinyin: "yè", th: "ใบ" },
      { cn: "捡", pinyin: "jiǎn", th: "หยิบ/เก็บ" },
      { cn: "红叶", pinyin: "hóngyè", th: "ใบไม้แดง" },
      { cn: "着急", pinyin: "zháo jí", th: "รีบร้อน/ร้อนใจ" },
      { cn: "着呢", pinyin: "zhene", th: "" },
      { cn: "表", pinyin: "biǎo", th: "นาฬิกาข้อมือ" },
      { cn: "坏", pinyin: "huài", th: "ไม่ดี/แย่/พัง" },
      { cn: "哎呀", pinyin: "āiyā", th: "อุ๊ย! (คำอุทาน)" },
      { cn: "停", pinyin: "tíng", th: "หยุด" },
      { cn: "该", pinyin: "gāi", th: "ควรจะ" },
      { cn: "电池", pinyin: "diànchí", th: "แบตเตอรี่" },
      { cn: "迟到", pinyin: "chídào", th: "มาสาย" },
      { cn: "好事", pinyin: "hǎoshì", th: "เรื่องดี" },
      { cn: "坏事", pinyin: "huàishì", th: "เรื่องร้าย" },
      { cn: "啦", pinyin: "la", th: "หละ/แล้ว (คำลงท้าย)" },
      { cn: "母亲", pinyin: "mǔqin", th: "มารดา (คำทางการ)" },
      { cn: "父亲", pinyin: "fùqin", th: "บิดา (คำทางการ)" },
      { cn: "地", pinyin: "de", th: "(คำเชื่อมกริยา)" },
      { cn: "结婚", pinyin: "jié hūn", th: "แต่งงาน" },
      { cn: "离婚", pinyin: "lí hūn", th: "หย่าร้าง" },
      { cn: "未婚夫", pinyin: "wèihūnfū", th: "คู่หมั้นชาย" },
      { cn: "未婚妻", pinyin: "wèihūnqī", th: "คู่หมั้นหญิง" },
      { cn: "将来", pinyin: "jiānglái", th: "อนาคต" },
      { cn: "这样", pinyin: "zhèyàng", th: "อย่างนี้" },
      { cn: "那样", pinyin: "nàyàng", th: "อย่างนั้น" }
    ],
    9: [
      { cn: "开会", pinyin: "kāi huì", th: "ประชุม" },
      { cn: "教学", pinyin: "jiàoxué", th: "การสอน" },
      { cn: "研讨会", pinyin: "yántǎohuì", th: "การสัมมนาทางวิชาการ" },
      { cn: "研讨", pinyin: "yántǎo", th: "ประชุมวิชาการ" },
      { cn: "经过", pinyin: "jīngguò", th: "ผ่าน/เดินผ่าน" },
      { cn: "向", pinyin: "xiàng", th: "มุ่งไป" },
      { cn: "问好", pinyin: "wèn hǎo", th: "ฝากทักทาย" },
      { cn: "捎", pinyin: "shāo", th: "ฝาก (ของ)" },
      { cn: "送", pinyin: "sòng", th: "ส่ง/มอบ" },
      { cn: "过去", pinyin: "guòqu", th: "ที่ผ่านมา" },
      { cn: "过来", pinyin: "guòlai", th: "เข้ามา/มานี่" },
      { cn: "辛苦", pinyin: "xīnkǔ", th: "ลำบาก" },
      { cn: "麻烦", pinyin: "máfan", th: "รบกวน" },
      { cn: "趟", pinyin: "tàng", th: "เที่ยว/รอบ/ครั้ง (ลักษณนามการเดินทาง)" },
      { cn: "进去", pinyin: "jìnqu", th: "เข้าไป" },
      { cn: "爱人", pinyin: "àiren", th: "คนรัก/คู่สมรส (สามี-ภรรยา)" },
      { cn: "办事", pinyin: "bàn shì", th: "จัดการ" },
      { cn: "慢", pinyin: "màn", th: "ช้า" },
      { cn: "上来", pinyin: "shànglai", th: "ขึ้นมา" },
      { cn: "马上", pinyin: "mǎshàng", th: "ทันที/เดี๋ยวนี้" },
      { cn: "开车", pinyin: "kāi chē", th: "ขับรถ" },
      { cn: "照相机", pinyin: "zhàoxiàngjī", th: "กล้องถ่ายรูป" },
      { cn: "照相", pinyin: "zhào xiàng", th: "ถ่ายรูป" },
      { cn: "座位", pinyin: "zuòwèi", th: "ที่นั่ง" },
      { cn: "注意", pinyin: "zhùyì", th: "ระวัง/ใส่ใจ" },
      { cn: "出土", pinyin: "chū tǔ", th: "ขุดออกมาจากดิน" },
      { cn: "文物", pinyin: "wénwù", th: "โบราณวัตถุ/มรดกทางวัฒนธรรม" },
      { cn: "展览", pinyin: "zhǎnlǎn", th: "นิทรรศการ" },
      { cn: "展览馆", pinyin: "zhǎnlǎnguǎn", th: "พิพิธภัณฑ์จัดแสดงนิทรรศการ" },
      { cn: "大约", pinyin: "dàyuē", th: "ประมาณ" },
      { cn: "要求", pinyin: "yāoqiú", th: "ความต้องการ/ข้อกำหนด" },
      { cn: "声", pinyin: "shēng", th: "(ลักษณนามเสียง)/เสียง" },
      { cn: "清楚", pinyin: "qīngchu", th: "ชัดเจน" },
      { cn: "师傅", pinyin: "shīfu", th: "(คนที่มีความเชี่ยวชาญในด้านต่างๆ)เชฟ/คนขับรถ/ช่าง" },
      { cn: "大使馆", pinyin: "dàshǐguǎn", th: "สถานทูต" },
      { cn: "大使", pinyin: "dàshǐ", th: "เอกอัครราชทูต" }
    ],
    10: [
      { cn: "过", pinyin: "guo", th: "เคย" },
      { cn: "住院", pinyin: "zhù yuàn", th: "นอนโรงพยาบาล" },
      { cn: "中医", pinyin: "zhōngyī", th: "หมอจีน/การแพทย์แผนจีน" },
      { cn: "苦", pinyin: "kǔ", th: "ขม" },
      { cn: "中成药", pinyin: "zhōngchéngyào", th: "ยาจีนสำเร็จรูป" },
      { cn: "甜", pinyin: "tián", th: "หวาน" },
      { cn: "摸", pinyin: "mō", th: "คลำ/สัมผัส" },
      { cn: "脉", pinyin: "mài", th: "ชีพจร" },
      { cn: "药方", pinyin: "yàofāng", th: "ใบสั่งยา" },
      { cn: "按摩", pinyin: "ànmó", th: "นวด" },
      { cn: "针灸", pinyin: "zhēnjiǔ", th: "ฝังเข็ม" },
      { cn: "方法", pinyin: "fāngfǎ", th: "วิธีการ" },
      { cn: "治", pinyin: "zhì", th: "รักษา" },
      { cn: "针", pinyin: "zhēn", th: "เข็ม" },
      { cn: "扎针", pinyin: "zhā zhēn", th: "ฝังเข็ม (กริยา)" },
      { cn: "细", pinyin: "xì", th: "ละเอียด/บาง" },
      { cn: "曾经", pinyin: "céngjīng", th: "เคย (ในอดีต)" },
      { cn: "第", pinyin: "dì", th: "ลำดับที่" },
      { cn: "中餐", pinyin: "zhōngcān", th: "อาหารจีน" },
      { cn: "烤鸭", pinyin: "kǎoyā", th: "เป็ดย่าง" },
      { cn: "烤", pinyin: "kǎo", th: "ย่าง" },
      { cn: "白薯", pinyin: "báishǔ", th: "มันเทศ" },
      { cn: "糖葫芦", pinyin: "tánghúlu", th: "ถังหูลู่" },
      { cn: "糖", pinyin: "táng", th: "น้ำตาล" },
      { cn: "什么的", pinyin: "shénmede", th: "อะไรทำนองนั้น" },
      { cn: "亲耳", pinyin: "qīn’ěr", th: "ได้ยินกับหูตนเอง" },
      { cn: "钢琴", pinyin: "gāngqín", th: "เปียโน" },
      { cn: "家", pinyin: "jiā", th: "ท่าน (ลักษณนามศิลปิน)" },
      { cn: "演奏", pinyin: "yǎnzòu", th: "บรรเลงเพลง" },
      { cn: "极了", pinyin: "jíle", th: "ที่สุด/มากๆ" },
      { cn: "小提琴", pinyin: "xiǎotíqín", th: "ไวโอลิน" },
      { cn: "协奏曲", pinyin: "xiézòuqǔ", th: "คอนแชร์โต" },
      { cn: "曲", pinyin: "qǔ", th: "บทเพลง" },
      { cn: "好听", pinyin: "hǎotīng", th: "เพราะ (เสียง)" },
      { cn: "还", pinyin: "huán", th: "คืน" },
      { cn: "嘛", pinyin: "ma", th: "ก็นั่นแหละ/สิ (คำลงท้าย)" }
      { cn: "哈尔滨", pinyin: "Hā’ěrbīn", th: "ฮาร์บิน" },
      { cn: "海南岛", pinyin: "Hǎinán Dǎo", th: "เกาะไหหลำ" },
      { cn: "泰山", pinyin: "Tài Shān", th: "ภูเขาไท่ซาน" },
      { cn: "西安", pinyin: "Xī’ān", th: "ซีอาน" },
      { cn: "敦煌", pinyin: "Dūnhuáng", th: "ตุนหวง" },
      { cn: "颐和园", pinyin: "Yíhé Yuán", th: "พระราชวังฤดูร้อน" },
      { cn: "故宫", pinyin: "Gùgōng", th: "พระราชวังต้องห้าม" },
      { cn: "长城", pinyin: "Chángchéng", th: "กำแพงเมืองจีน" },
      { cn: "《黄河》", pinyin: "Huáng Hé", th: "บทเพลงเปียโน แม่น้ำเหลือง" },
      { cn: "《梁祝》", pinyin: "Liáng-Zhù", th: "บทเพลงไวโอลิน คู่รักผีเสื้อ" }
    ],
    11: [
      { cn: "前天", pinyin: "qiántiān", th: "เมื่อวานซืน" },
      { cn: "后天", pinyin: "hòutiān", th: "มะรืน" },
      { cn: "导游", pinyin: "dǎoyóu", th: "ไกด์" },
      { cn: "研究生", pinyin: "yánjiūshēng", th: "นักศึกษาปริญญาโท" },
      { cn: "打工", pinyin: "dǎ gōng", th: "ทำงานพิเศษ" },
      { cn: "利用", pinyin: "lìyòng", th: "ใช้ประโยชน์จาก" },
      { cn: "假期", pinyin: "jiàqī", th: "ช่วงปิดเทอม" },
      { cn: "旅行社", pinyin: "lǚxíngshè", th: "บริษัททัวร์" },
      { cn: "组织", pinyin: "zǔzhī", th: "องค์กร/จัดตั้ง" },
      { cn: "老板", pinyin: "lǎobǎn", th: "เถ้าแก่/บอส" },
      { cn: "需要", pinyin: "xūyào", th: "ต้องการ" },
      { cn: "经常", pinyin: "jīngcháng", th: "บ่อยๆ" },
      { cn: "收集", pinyin: "shōují", th: "สะสม/รวบรวม" },
      { cn: "一……就……", pinyin: "yī……jiù……", th: "พอ...ก็..." },
      { cn: "安排", pinyin: "ānpái", th: "จัดแจง/ตาราง" },
      { cn: "帮助", pinyin: "bāngzhù", th: "ช่วยเหลือ" },
      { cn: "帮", pinyin: "bāng", th: "ช่วย" },
      { cn: "高铁", pinyin: "gāotiě", th: "รถไฟความเร็วสูง" },
      { cn: "铁路", pinyin: "tiělù", th: "ทางรถไฟ" },
      { cn: "风光", pinyin: "fēngguāng", th: "ทิวทัศน์" },
      { cn: "商量", pinyin: "shāngliang", th: "ปรึกษาหารือ" },
      { cn: "故乡", pinyin: "gùxiāng", th: "บ้านเกิด" },
      { cn: "自由", pinyin: "zìyóu", th: "อิสระ" },
      { cn: "活动", pinyin: "huódòng", th: "กิจกรรม" },
      { cn: "马马虎虎", pinyin: "mǎmǎhūhū", th: "งูๆ ปลาๆ/พอใช้ได้" },
      { cn: "老外", pinyin: "lǎowài", th: "ชาวต่างชาติ" },
      { cn: "呀", pinyin: "ya", th: "นะ (คำอุทาน)" },
      { cn: "鼻子", pinyin: "bízi", th: "จมูก" },
      { cn: "头发", pinyin: "tóufa", th: "เส้นผม" },
      { cn: "眼睛", pinyin: "yǎnjing", th: "ดวงตา" },
      { cn: "声调", pinyin: "shēngdiào", th: "วรรณยุกต์" },
      { cn: "互相", pinyin: "hùxiāng", th: "ซึ่งกันและกัน" },
      { cn: "希望", pinyin: "xīwàng", th: "หวังว่า" }
    ],
    12: [
      { cn: "护照", pinyin: "hùzhào", th: "พาสปอร์ต" },
      { cn: "半天", pinyin: "bàntiān", th: "ตั้งนาน/ครึ่งวัน" },
      { cn: "着", pinyin: "zháo", th: "สำเร็จ (ใช้หลังกริยา)" },
      { cn: "放", pinyin: "fàng", th: "วาง/ใส่" },
      { cn: "签证", pinyin: "qiānzhèng", th: "วีซ่า" },
      { cn: "手提包（儿）", pinyin: "shǒutíbāor", th: "กระเป๋าถือ" },
      { cn: "包（儿）", pinyin: "bāor", th: "กระเป๋า" },
      { cn: "交", pinyin: "jiāo", th: "ส่ง/มอบให้" },
      { cn: "好好儿", pinyin: "hǎohāor", th: "อย่างดี/ให้ดี" },
      { cn: "大衣", pinyin: "dàyī", th: "เสื้อโค้ท" },
      { cn: "口袋", pinyin: "kǒudai", th: "กระเป๋าเสื้อ/กางเกง" },
      { cn: "丢三落四", pinyin: "diūsān-làsì", th: "ขี้ลืม/ลืมนั่นลืมนี่" },
      { cn: "丢", pinyin: "diū", th: "ทำหาย" },
      { cn: "落", pinyin: "là", th: "ลืมทิ้งไว้" },
      { cn: "可", pinyin: "kě", th: "จริงๆ (ใช้เน้นย้ำ)" },
      { cn: "球迷", pinyin: "qiúmí", th: "แฟนบอล" },
      { cn: "程度", pinyin: "chéngdù", th: "ระดับ" },
      { cn: "为了", pinyin: "wèile", th: "เพื่อที่จะ" },
      { cn: "正常", pinyin: "zhèngcháng", th: "ปกติ" },
      { cn: "承认", pinyin: "chéngrèn", th: "ยอมรับ" },
      { cn: "发狂", pinyin: "fā kuáng", th: "บ้าคลั่ง" },
      { cn: "锦标赛", pinyin: "jǐnbiāosài", th: "การแข่งขันชิงแชมป์" },
      { cn: "期间", pinyin: "qījiān", th: "ในช่วงเวลา" },
      { cn: "像", pinyin: "xiàng", th: "เหมือนกับ" },
      { cn: "生病", pinyin: "shēng bìng", th: "ป่วย" },
      { cn: "白天", pinyin: "báitiān", th: "กลางวัน" },
      { cn: "精神", pinyin: "jīngshen", th: "จิตวิญญาณ/ความกระปรี้กระเปร่า" },
      { cn: "贴", pinyin: "tiē", th: "ติด/แปะ" },
      { cn: "通知", pinyin: "tōngzhī", th: "ประกาศ" },
      { cn: "暂停", pinyin: "zàntíng", th: "หยุดชั่วคราว" },
      { cn: "营业", pinyin: "yíngyè", th: "เปิดกิจการ/เวลาทำการ" },
      { cn: "算", pinyin: "suàn", th: "นับว่า" },
      { cn: "现场", pinyin: "xiànchǎng", th: "สถานที่จริง/สดๆ" },
      { cn: "亲眼", pinyin: "qīnyǎn", th: "เห็นกับตาตนเอง" },
      { cn: "准", pinyin: "zhǔn", th: "อนุญาต" },
      { cn: "辞职", pinyin: "cí zhí", th: "ลาออก" },
      { cn: "最后", pinyin: "zuìhòu", th: "สุดท้าย" },
      { cn: "成", pinyin: "chéng", th: "สำเร็จ" },
      { cn: "佩服", pinyin: "pèifú", th: "เลื่อมใส/นับถือ" },
      { cn: "棒", pinyin: "bàng", th: "ยอดเยี่ยม/เก่ง" }
    ]
  }
};
